name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    uses: ./.github/workflows/reusable-main-deployment.yml
    with:
      target-env: zaraco
    secrets: inherit
