name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
  NEXT_PUBLIC_CONFIG_EXPERIENCE: ${{vars.NEXT_PUBLIC_CONFIG_EXPERIENCE}}
  NEXT_PUBLIC_CONFIG_HIGHLIGHTS: ${{vars.NEXT_PUBLIC_CONFIG_HIGHLIGHTS}}
  NEXT_PUBLIC_CONFIG_PORTFOLIO: ${{vars.NEXT_PUBLIC_CONFIG_PORTFOLIO}}
  NEXT_PUBLIC_CONFIG_PROFILE: ${{vars.NEXT_PUBLIC_CONFIG_PROFILE}}
  NEXT_PUBLIC_CONFIG_RECOMMENDATIONS: ${{vars.NEXT_PUBLIC_CONFIG_RECOMMENDATIONS}}
  NEXT_PUBLIC_SITE_NAME: ${{vars.NEXT_PUBLIC_SITE_NAME}}
  NEXT_PUBLIC_SITE_URL: ${{vars.NEXT_PUBLIC_SITE_URL}}

jobs:
  build_and_deploy:
    name: Build and deploy
    environment: armanco
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Check Prettier Formatting
        run: npm run prettier:check

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
