name: Pull Request Test
on: pull_request

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Check Prettier Formatting
        run: npm run prettier:check

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build
