name: Pull Request Preview
on: pull_request_target

jobs:
  build_and_deploy:
    name: Build and Deploy
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      target-env: armanco
    secrets: inherit
